# ===================================================================
# GLOBAL DEFAULT CONNECTION SETTINGS (WinRM over Private IPs)
# ===================================================================
[all:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_server_cert_validation=ignore

# ===================================================================
# HOST POOL 1 (Client / Environment A 
# ===================================================================
[hostpool_a]
10.0.0.16 session_host_name=avdhost-2.corps.com host_pool=hostpool resource_group=avd subscription_id=6d444e88-4585-49e6-9a3d-25b83dfe35bf

[hostpool_a:vars]
ansible_user=saqlin
ansible_password=Ready4summer@123

# ===================================================================
# HOST POOL 2 (Client / Environment B - VNet 10.10.x.x)
# ===================================================================
[hostpool_b]
10.0.0.15 session_host_name=avd-patch-0.corps.com host_pool=DomainHP resource_group=avd subscription_id=6d444e88-4585-49e6-9a3d-25b83dfe35bf
10.0.0.14 session_host_name=avd-patch-1.corps.com host_pool=DomainHP resource_group=avd subscription_id=6d444e88-4585-49e6-9a3d-25b83dfe35bf
10.0.0.12 session_host_name=avd-patch-2.corps.com host_pool=DomainHP resource_group=avd subscription_id=6d444e88-4585-49e6-9a3d-25b83dfe35bf

[hostpool_b:vars]
ansible_user=azadmin
ansible_password=Ready4summer@123

# ===================================================================
# ENTRA HOST POOL (Mixed Credentials in Same Host Pool)
# ===================================================================
[entra_hostpool]
10.20.0.4 session_host_name=avd-entra-0 host_pool=EntraHP resource_group=AVD-PATCH-ENTRA subscription_id=6d444e88-4585-49e6-9a3d-25b83dfe35bf

[entra_hostpool:vars]
ansible_user=azadmin
ansible_password=Ready4summer@123